apiVersion: v1
kind: ConfigMap
metadata:
  name: fetch-model-scripts
data:
  fetch_model.sh: |-
    #!/usr/bin/bash
    apt-get update -y && \
      apt-get install -y --no-install-recommends \
      git git-lfs rsync
    git lfs install
    cd /tmp
    echo "Saving model into /tmp..."
    time git clone -c http.sslverify=false --depth=1 https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/${MODEL_PATH}; echo "cloned"
    echo "Copying to the bucket"
    time rsync --inplace --info=progress2 --exclude .git -a /tmp/gemma-2b/ /data/gemma-2b/ || exit 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader-2b
  labels:
    app: data-loader-2b
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: data-loader-2b
    spec:
      restartPolicy: OnFailure
      serviceAccountName: bucket-access-sa
      containers:
      - name: job
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
        - /scripts/fetch_model.sh
        resources:
          requests:
            cpu: "1"
            memory: "10Gi"
          limits:
            cpu: "2"
            memory: "12Gi"
        env:
        - name: MODEL_PATH
          value: "google/gemma-2b"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_token
        - name: HF_USERNAME
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_username
        - name: BUCKET_NAME
          value: <CLUSTER_PREFIX>-<PROJECT_ID>-model-bucket
        volumeMounts:
        - mountPath: "/scripts/"
          name: scripts-volume
          readOnly: true
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: false

      volumes:
      - name: scripts-volume
        configMap:
          defaultMode: 0700
          name: fetch-model-scripts
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: false
          volumeAttributes:
            bucketName: <CLUSTER_PREFIX>-<PROJECT_ID>-model-bucket
            mountOptions: "implicit-dirs,metadata-cache:ttl-secs:-1,file-cache:max-size-mb:-1,file-cache:cache-file-for-range-read:true,file-cache:enable-parallel-downloads:true"
            gcsfuseLoggingSeverity: warning

      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: NoSchedule
      - key: "app.stateful/component"
        operator: "Equal"
        value: "model-train"
        effect: NoSchedule
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
